export const events = [
    {
        dataInicio: "2024-01-01",
        dataFim: "2024-01-01",
        cor: "#e06665",
        descricao: "Confraternização universal - Feriado nacional",
        campusId: 1,
    },
     {
        dataInicio: "2024-01-02",
        dataFim: "2024-01-31",
        cor: "#cccccc",
        descricao: "Férias docentes e acadêmicas",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-01",
        dataFim: "2024-02-02",
        cor: "#cccccc",
        descricao: "Formação pedagógica/Formação SUAP",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-05",
        dataFim: "2024-02-05",
        cor: "#ff0000",
        descricao: "Formação pedagógica/Formação SUAP",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-06",
        dataFim: "2024-02-07",
        cor: "#ffe59a",
        descricao: "Planejamento pedagógico Coletivo ou por Área de todos os cursos",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-06",
        dataFim: "2024-02-08",
        cor: "#cccccc",
        descricao: "Matrículas 2ª Chamada complementar processo seletivo 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-12",
        dataFim: "2024-02-14",
        cor: "#fe9900",
        descricao: "Recesso escolar/carnaval",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-15",
        dataFim: "2024-02-15",
        cor: "#ffff00",
        descricao: "Inicio do ano letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-17",
        dataFim: "2024-02-17",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-02-24",
        dataFim: "2024-02-24",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-01",
        dataFim: "2024-03-01",
        cor: "#92c47d",
        descricao: "Prazo final para ajuste de matrícula (alteração de estudantes nas turmas) dos Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
      {
        dataInicio: "2024-03-02",
        dataFim: "2024-03-02",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-09",
        dataFim: "2024-03-09",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-15",
        dataFim: "2024-03-15",
        cor: "#cccccc",
        descricao: "Prazo final para entrega do Plano de Ensino 2024.1",
        campusId: 1,
    },
      {
        dataInicio: "2024-03-16",
        dataFim: "2024-03-16",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-18",
        dataFim: "2024-03-19",
        cor: "#cccccc",
        descricao: "Formação pedagógica",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-22",
        dataFim: "2024-03-22",
        cor: "#cccccc",
        descricao: "Prazo final para entrega do Plano Trabalho Docente 2024.1",
        campusId: 1,
    },
      {
        dataInicio: "2024-03-23",
        dataFim: "2024-03-23",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-28",
        dataFim: "2024-03-28",
        cor: "#fd9900",
        descricao: "Recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-03-29",
        dataFim: "2024-03-29",
        cor: "#e06665",
        descricao: "Paixão de cristo-feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-06",
        dataFim: "2024-04-06",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-08",
        dataFim: "2024-04-19",
        cor: "#cccccc",
        descricao: "Pré-conselho de classe pedagógico - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-13",
        dataFim: "2024-04-13",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-17",
        dataFim: "2024-04-18",
        cor: "#cccccc",
        descricao: "Formação pedagógica",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-20",
        dataFim: "2024-04-20",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-21",
        dataFim: "2024-04-21",
        cor: "#e06665",
        descricao: "Tiradentes - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-25",
        dataFim: "2024-04-25",
        cor: "#ffff00",
        descricao: "Final do 1º bimestre do ano letivo 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-26",
        dataFim: "2024-04-26",
        cor: "#ffff00",
        descricao: "Inicio do 1º bimestre do ano letivo 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-27",
        dataFim: "2024-04-27",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-04-30",
        dataFim: "2024-04-30",
        cor: "#92c47d",
        descricao: "Prazo final para lançamento de resultados parciais (1ºbim) SUAP - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-01",
        dataFim: "2024-05-01",
        cor: "#e06665",
        descricao: "Dia Mundial do Trabalho - feriado naciona",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-04",
        dataFim: "2024-05-04",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-06",
        dataFim: "2024-05-06",
        cor: "#b4a3e7",
        descricao: "Prazo final para solicitação de revisão dos resultados parciais - SUAP (1ºBim)",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-07",
        dataFim: "2024-05-10",
        cor: "#c37fee",
        descricao: "Conselhos de classe/ coletivos pedagógicos - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
     {
        dataInicio: "2024-05-11",
        dataFim: "2024-05-11",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-13",
        dataFim: "2024-05-13",
        cor: "#d039e3",
        descricao: "Conselhos de Classe extraordinários posteriores aos prazos de solicitação do estudante de revisão dos resultados das avaliações parciais",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-15",
        dataFim: "2024-05-15",
        cor: "#cccccc",
        descricao: "Cepechinho - Evento local - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-17",
        dataFim: "2024-05-17",
        cor: "#5e8906",
        descricao: "Prazo final para lançamento de resultados parciais (1ºBim) SUAP - após a revisão dos resultados das avaliações parciais - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
     {
        dataInicio: "2024-05-18",
        dataFim: "2024-05-18",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
     {
        dataInicio: "2024-05-25",
        dataFim: "2024-05-25",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-30",
        dataFim: "2024-05-30",
        cor: "#fe9900",
        descricao: "Corpus Christi - recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-05-31",
        dataFim: "2024-05-31",
        cor: "#fe9900",
        descricao: "Recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-01",
        dataFim: "2024-06-01",
        cor: "#fe9900",
        descricao: "Recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-03",
        dataFim: "2024-06-06",
        cor: "#cccccc",
        descricao: "Semana do Meio Ambiente",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-05",
        dataFim: "2024-06-05",
        cor: "#92c47d",
        descricao: "Dia Mundial do Meio ambiente",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-07",
        dataFim: "2024-06-07",
        cor: "#e06665",
        descricao: "Feriado municipal - Padroeiro da cidade",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-09",
        dataFim: "2024-06-09",
        cor: "#92c47d",
        descricao: "Dia Nacional de Imunização",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-15",
        dataFim: "2024-06-15",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-21",
        dataFim: "2024-06-21",
        cor: "#941107",
        descricao: "Mostra de curso - Técnicos Integrados ao Ensino Médio, Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-22",
        dataFim: "2024-06-22",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-25",
        dataFim: "2024-06-26",
        cor: "#cccccc",
        descricao: "Formação Pedagógica",
        campusId: 1,
    },
    {
        dataInicio: "2024-06-29",
        dataFim: "2024-06-29",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-01",
        dataFim: "2024-07-01",
        cor: "#5e8906",
        descricao: "Prazo final para lançamento de resultados parciais no sistema acadêmico - Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-02",
        dataFim: "2024-07-02",
        cor: "#b4a3e7",
        descricao: "Prazo final para solicitação de revisão dos resultados parciais SUAP (2ºBim) - Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-03",
        dataFim: "2024-07-03",
        cor: "#c37fee",
        descricao: "Conselho de classe pedagógico - cursos técnicos subsequentes | Coletivo pedagógico extraordinários - Cursos de Graduação - Divulgação do parecer referente a solicitação de revisão dos resultados das avaliações parciais SUAP - Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-04",
        dataFim: "2024-07-04",
        cor: "#ff0000",
        descricao: "Prazo final para solicitação de revisão dos resultados finais de Conselho de Classe Pedagógico - Cursos Técnicos Subsequentes | Coletivo pedagógico extraordinários - Cursos de Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-05",
        dataFim: "2024-07-05",
        cor: "#ffff00",
        descricao: "- Final do 2° bimestre do ano letivo 2024 - Final do período letivo 2024.1 - Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-08",
        dataFim: "2024-07-22",
        cor: "#cccccc",
        descricao: "Férias docentes e acadêmicas",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-23",
        dataFim: "2024-07-23",
        cor: "#ffff00",
        descricao: "- Início do semestre letivo 2024.2 - Cursos Técnicos Subsequentes e Graduação - Início do 3° Bimestre do ano letivo 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-23",
        dataFim: "2024-07-24",
        cor: "#ffff00",
        descricao: "Planejamento Pedagógico Coletivo ou por área dos Cursos Técnicos Integrados ao Ensino Médio, Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-25",
        dataFim: "2024-07-25",
        cor: "#5e8906",
        descricao: "Prazo final para lançamento de resultados parciais (2ºBim) SUAP - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-27",
        dataFim: "2024-07-27",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-07-29",
        dataFim: "2024-07-31",
        cor: "#c37fee",
        descricao: "Conselhos de classe/coletivos pedagógicos - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-05",
        dataFim: "2024-08-05",
        cor: "#f704f7",
        descricao: "Conselhos de Classe extraordinários posteriores aos prazos de solicitação do estudante de revisão dos resultados das avaliações parciais - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-05",
        dataFim: "2024-08-09",
        cor: "#cccccc",
        descricao: "Período para solicitação de certificação de conhecimentos anteriores e de aproveitamento de estudos anteriores - Cursos Técnicos Subsequentes e Cursos de Graduação 2024.2",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-09",
        dataFim: "2024-08-09",
        cor: "#cccccc",
        descricao: "Prazo final para ajuste de matrícula (alteração de estudantes nas turmas) dos Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-10",
        dataFim: "2024-08-10",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-17",
        dataFim: "2024-08-17",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-23",
        dataFim: "2024-08-23",
        cor: "#cccccc",
        descricao: "Prazo final para entrega do Plano de Ensino 2024.2",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-24",
        dataFim: "2024-08-24",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-30",
        dataFim: "2024-08-30",
        cor: "#cccccc",
        descricao: "Prazo final para entrega do Plano Trabalho Docente 2024.2",
        campusId: 1,
    },
    {
        dataInicio: "2024-08-31",
        dataFim: "2024-08-31",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-03",
        dataFim: "2024-09-03",
        cor: "#cccccc",
        descricao: "Dia do Biólogo - Evento do Curso de Licenciatura em Ciências Biológicas",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-07",
        dataFim: "2024-09-07",
        cor: "#e06665",
        descricao: "Independência do Brasil - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-10",
        dataFim: "2024-09-10",
        cor: "#cccccc",
        descricao: "Prazo máximo para emissão da análise de solicitação de certificação de conhecimentos anteriores e de aproveitamento de estudos anteriores - Cursos Técnicos Subsequentes e Cursos de Graduação 2024.2",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-14",
        dataFim: "2024-09-14",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-16",
        dataFim: "2024-09-20",
        cor: "#cccccc",
        descricao: "Semana da SEPAE",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-16",
        dataFim: "2024-09-27",
        cor: "#cccccc",
        descricao: "Pré-conselho de classe pedagógico - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-21",
        dataFim: "2024-09-21",
        cor: "#46bcc6",
        descricao: "Dia Nacional de luta da pessoa com deficiência",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-21",
        dataFim: "2024-09-21",
        cor: "#cccccc",
        descricao: "Sábado letivo - Encontro de Egressos - Cursos Técnicos Integrados ao Ensino Médio, Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-24",
        dataFim: "2024-09-24",
        cor: "#cccccc",
        descricao: "Formação pedagógica",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-26",
        dataFim: "2024-09-26",
        cor: "#ffff00",
        descricao: "Final do 3º Bimestre do ano letivo de 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-27",
        dataFim: "2024-09-27",
        cor: "#ffff00",
        descricao: "Início do 4º Bimestre do ano letivo de 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-09-28",
        dataFim: "2024-09-28",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
      {
        dataInicio: "2024-10-04",
        dataFim: "2024-10-04",
        cor: "#5e8906",
        descricao: "Prazo final para lançamento de resultados parciais (3º Bim) SUAP - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-05",
        dataFim: "2024-10-05",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-06",
        dataFim: "2024-10-06",
        cor: "#de9278",
        descricao: "Prova do processo seletivo (data provável)",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-07",
        dataFim: "2024-10-07",
        cor: "#b3a3e7",
        descricao: "Prazo final para solicitação de revisão dos resultados parciais SUAP (3º Bim) - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-08",
        dataFim: "2024-10-11",
        cor: "#c37fee",
        descricao: "Conselhos de classe/ coletivos pedagógicos - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-12",
        dataFim: "2024-10-12",
        cor: "#e06665",
        descricao: "Nossa Senhora Aparecida - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-15",
        dataFim: "2024-10-15",
        cor: "#92c47d",
        descricao: "Dia do(a) Professor(a)",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-16",
        dataFim: "2024-10-16",
        cor: "#ec0ceb",
        descricao: "Conselhos de classe extraordinários posteriores aos prazos de solicitação do estudante de revisão dos resultados das avaliações parciais - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-18",
        dataFim: "2024-10-18",
        cor: "#b4a3e7",
        descricao: "Prazo final para lançamento de resultados parciais (3º Bim) SUAP - após a revisão dos resultados das avaliações parciais - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-18",
        dataFim: "2024-10-18",
        cor: "#cccccc",
        descricao: "CEPECHART - Evento local - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-19",
        dataFim: "2024-10-19",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-23",
        dataFim: "2024-10-25",
        cor: "#cccccc",
        descricao: "Semana do Livro e da Biblioteca",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-26",
        dataFim: "2024-10-26",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-28",
        dataFim: "2024-10-28",
        cor: "#fe9900",
        descricao: "Dia do servidor público - recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-10-01",
        dataFim: "2024-10-31",
        cor: "#cccccc",
        descricao: "Mês Nacional da Ciência e Tecnologia",
        campusId: 1,
    },
     {
        dataInicio: "2024-11-02",
        dataFim: "2024-11-02",
        cor: "#e06665",
        descricao: "Finados - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-06",
        dataFim: "2024-11-07",
        cor: "#cccccc",
        descricao: "Formação Pedagógica",
        campusId: 1,
    },
     {
        dataInicio: "2024-11-09",
        dataFim: "2024-11-09",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-11",
        dataFim: "2024-11-14",
        cor: "#cccccc",
        descricao: "Biotecando - Evento específico do Curso Técnico em Biotecnologia Integrado ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-15",
        dataFim: "2024-11-15",
        cor: "#e06665",
        descricao: "Proclamação da República - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-16",
        dataFim: "2024-11-16",
        cor: "#fe9900",
        descricao: "Recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-18",
        dataFim: "2024-11-22",
        cor: "#cccccc",
        descricao: "XIII Semana de Integração (Ensino, Pesquisa, Extensão, Inovação)",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-18",
        dataFim: "2024-11-20",
        cor: "#5e8906",
        descricao: "XII Ciclo de Palestras - Evento específico do Curso Técnico Subsequente em Massoterapia",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-18",
        dataFim: "2024-11-29",
        cor: "#e06665",
        descricao: "Pré-conselho de classe pedagógico - Cursos Técnicos Integrado ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-20",
        dataFim: "2024-11-20",
        cor: "#92c47d",
        descricao: "Dia Nacional da Consciência Negra e IX Consciência Negra em Debate",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-21",
        dataFim: "2024-11-22",
        cor: "#cccccc",
        descricao: "II Simpósio de Inovação e Tecnologia do Norte Paranaense - Inovatec/PR",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-22",
        dataFim: "2024-11-22",
        cor: "#cccccc",
        descricao: "Feira de estágio(s)",
        campusId: 1,
    },
   
    {
        dataInicio: "2024-11-23",
        dataFim: "2024-11-23",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-11-30",
        dataFim: "2024-11-30",
        cor: "#46bcc6",
        descricao: "Sabado Letivo",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-04",
        dataFim: "2024-12-04",
        cor: "#5e8906",
        descricao: "Prazo final para lançamento de resultados parciais (4º Bim) SUAP - Cursos Técnicos Integrados ao Ensino Médio, Técnicos Subsequentes e Graduação (2024.2)",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-05",
        dataFim: "2024-12-06",
        cor: "#b4a3e7",
        descricao: "Prazo final para solicitação de revisão dos resultados parciais SUAP - Cursos Técnicos Integrados ao Ensino Médio (4ºbim), Técnicos Subsequentes e Graduação (2024.2)",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-06",
        dataFim: "2024-12-06",
        cor: "#ffff00",
        descricao: "Final do período letivo 2024.2 - Cursos Técnicos Subsequentes e Graduação e final do 4º Bim do ano letivo 2024",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-10",
        dataFim: "2024-12-10",
        cor: "#e06665",
        descricao: "Feriado Municipal: Aniversário da Cidade de Londrina/PR",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-09",
        dataFim: "2024-12-11",
        cor: "#c37fee",
        descricao: "Conselho de classe pedagógico - Cursos Técnicos Integrado ao Ensino Médio e Técnicos Subsequentes | Coletivo pedagógico extraordinários - Cursos de Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-12",
        dataFim: "2024-12-13",
        cor: "#c37fee",
        descricao: "Prazo final para solicitação de revisão dos resultados finais de Conselho de classe pedagógico - Cursos Técnicos Integrados ao Ensino Médio e Técnicos Subsequentes | Coletivo pedagógico extraordinários - Cursos de Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-16",
        dataFim: "2024-12-16",
        cor: "#e312e2",
        descricao: "Conselhos de Classe extraordinários posteriores aos prazos de solicitação do estudante de revisão dos resultados das avaliações finais - Cursos Técnicos Integrados ao Ensino Médio e Técnicos Subsequentes | Coletivo pedagógico extraordinários - Cursos de Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-17",
        dataFim: "2024-12-17",
        cor: "#b4a3e7",
        descricao: "Divulgação do parecer referente à solicitação de revisão dos resultados das avaliações finais SUAP - Cursos Técnicos Integrados ao Ensino Médio, Cursos Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-18",
        dataFim: "2024-12-18",
        cor: "#7298a8",
        descricao: "Reunião de pais/responsáveis, estudantes e comunidade - Cursos Técnicos Integrados ao Ensino Médio",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-19",
        dataFim: "2024-12-19",
        cor: "#cccccc",
        descricao: "Prazo final para lançamento de resultados parciais e/ou finais no sistema acadêmico e fechamento e entrega de diário de classe à Direção de Ensino 2024.2 - Cursos Técnicos Integrados ao Ensino Médio, Técnicos Subsequentes e Graduação",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-24",
        dataFim: "2024-12-24",
        cor: "#1deb1c",
        descricao: "Recesso acadêmico e administrativo",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-25",
        dataFim: "2024-12-25",
        cor: "#fe9900",
        descricao: "Natal - feriado nacional",
        campusId: 1,
    },
    {
        dataInicio: "2024-12-29",
        dataFim: "2024-12-29",
        cor: "#cccccc",
        descricao: "Criação do IFPR e da Rede Federal de Educação profissional, científica e tecnológica",
        campusId: 1,
    }
]
